# Generated by Django 4.1.7 on 2023-02-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='usernmae',
            new_name='username',
        ),
    ]
