# Generated by Django 4.1.7 on 2023-02-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prouduct',
            new_name='Product',
        ),
    ]
